# Generated by Django 4.0.4 on 2022-06-26 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='trend', to=settings.AUTH_USER_MODEL),
        ),
    ]
