# Generated by Django 4.0.4 on 2022-06-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendsentiment',
            name='trend',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trend'),
        ),
    ]
