# Generated by Django 4.0.4 on 2022-06-17 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trendsentiment_trend'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(null=True)),
                ('reply_count', models.IntegerField(null=True)),
                ('retweet_count', models.IntegerField(null=True)),
                ('min_followers', models.IntegerField(null=True)),
                ('max_followers', models.IntegerField(null=True)),
                ('average_followers', models.IntegerField(null=True)),
                ('calculated_upto', models.BigIntegerField(blank=True, null=True)),
                ('trend', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trend')),
            ],
        ),
        migrations.CreateModel(
            name='TrendSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, null=True)),
                ('count', models.IntegerField(null=True)),
                ('trend_stats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trendstats')),
            ],
        ),
    ]
