# Generated by Django 4.0.4 on 2022-06-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trendsentiment_top_neg_1_trendsentiment_top_neg_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendsentiment',
            old_name='neg_sub_count',
            new_name='obj_count',
        ),
        migrations.RenameField(
            model_name='trendsentiment',
            old_name='neu_sub_count',
            new_name='sub_count',
        ),
        migrations.RemoveField(
            model_name='trendsentiment',
            name='pos_sub_count',
        ),
        migrations.AlterField(
            model_name='trendsentiment',
            name='calculated_upto',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
