# Generated by Django 4.0.4 on 2022-06-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_neg_sub_count_trendsentiment_obj_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='tweets',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='trend', to='core.tweet'),
        ),
    ]
