# Generated by Django 4.0.4 on 2022-06-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_trend_tweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tid',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
