# Generated by Django 4.0.4 on 2022-05-22 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(default=None, max_length=255)),
                ('consumer_secret', models.CharField(default=None, max_length=255)),
                ('access_token', models.CharField(default=None, max_length=255)),
                ('access_secret', models.CharField(default=None, max_length=255)),
                ('bearer_token', models.CharField(default=None, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.IntegerField(default=0)),
                ('query', models.CharField(default=None, max_length=255)),
                ('duration', models.IntegerField(default=0)),
                ('elapsed', models.IntegerField(default=0)),
                ('crawler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_data', to='crawler.crawler')),
            ],
        ),
    ]
