# Generated by Django 4.0.4 on 2022-05-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamdata',
            name='query',
            field=models.CharField(blank=True, default='', help_text='List of comma-separated keywords to filter the stream', max_length=255),
        ),
    ]
